---
name: Herencia
locale: es
type: learning
beta: false
teacher_info: ''
language: ruby
id_format: "%05d"
order:
- 1
- 2
- 17
- 3
- 18
- 19
- 20
- 10
- 11
- 21
- 22
- 23
- 24
- 25
- 26
private: false
