---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `gritar`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `salud`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `sin_vida?`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `recibir_danio!`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `sabe_correr?`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe implementar el método `regenerarse!`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `gritar`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `salud`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `sin_vida?`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `recibir_danio!`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `sabe_correr?`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe implementar el método `regenerarse!`"
  checked: true
name: El regreso de los zombis
