---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`initialize`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`utilizar!`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`cargar_a_tope!`"
  checked: true
name: No repitan conmigo
